- Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV2.xcdatamodel/contents
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/Contacts.swift
- Meshtastic/Views/Messages/UserMessageList.swift
- Meshtastic/Views/Settings/Config/Module/ExternalNotificationConfig.swift
* Fix channel mute update
* Add waypoint to core data
* Add Use PWM to external notification config
> 2.0.6 working changes

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Protobufs/config.pb.swift
- Meshtastic/Protobufs/mesh.pb.swift
- Meshtastic/Protobufs/module_config.pb.swift
- Meshtastic/Protobufs/portnums.pb.swift
- Meshtastic/Views/Messages/Contacts.swift
- Meshtastic/Views/Settings/About.swift
- Meshtastic/Views/Settings/Config/BluetoothConfig.swift
- Meshtastic/Views/Settings/Config/DeviceConfig.swift
- Meshtastic/Views/Settings/Config/DisplayConfig.swift
- Meshtastic/Views/Settings/Config/LoRaConfig.swift
- Meshtastic/Views/Settings/Config/Module/CannedMessagesConfig.swift
- Meshtastic/Views/Settings/Config/Module/ExternalNotificationConfig.swift
- Meshtastic/Views/Settings/Config/Module/MQTTConfig.swift
- Meshtastic/Views/Settings/Config/Module/RangeTestConfig.swift
- Meshtastic/Views/Settings/Config/Module/SerialConfig.swift
- Meshtastic/Views/Settings/Config/Module/TelemetryConfig.swift
- Meshtastic/Views/Settings/Config/NetworkConfig.swift
- Meshtastic/Views/Settings/Config/PositionConfig.swift
- Meshtastic/Views/Settings/ShareChannels.swift
- Meshtastic/Views/Settings/UserConfig.swift
> 2.0.7 Working Changes

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Export/WriteCsvFile.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/Extensions.swift
- Meshtastic/Views/Nodes/EnvironmentMetricsLog.swift
Format temperature using the users setting from Settings > Language & Region > Temperature
Fix potential timer crash on BLEManager
> Format temperature using the user setting

- Meshtastic/Enums/DeviceRoles.swift
Suggested updated role wording to improve clarity for users.
> Role description suggestions

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Views/Map/Custom/MapViewSwiftUI.swift
- Meshtastic/Views/Nodes/DeviceMetricsLog.swift
- Meshtastic/Views/Nodes/NodeMap.swift
- Meshtastic/Views/Settings/UserConfig.swift
Licensed User Mock up on User Config view
> Working Changes for 2.0.14

- Meshtastic/Enums/AppSettingsEnums.swift
- Meshtastic/Extensions/FileManager.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Helpers/ConnectedDevice.swift
- Meshtastic/Views/Helpers/LoRaSignalStrengthIndicator.swift
- Meshtastic/Views/Helpers/Node/NodeInfoView.swift
- Meshtastic/Views/Map/Custom/MapViewSwiftUI.swift
- Meshtastic/Views/Messages/UserMessageList.swift
- Meshtastic/Views/Nodes/DeviceMetricsLog.swift
- Meshtastic/Views/Nodes/EnvironmentMetricsLog.swift
- Meshtastic/Views/Nodes/NodeList.swift
- Meshtastic/Views/Nodes/NodeMap.swift
- Meshtastic/Views/Nodes/PositionLog.swift
- Meshtastic/Views/Settings/AppSettings.swift
- en.lproj/Localizable.strings
* More Emoji
* Signal Strength indicators for lora
* Restrict tile overlays to zoom levels
> * New Tile Server

- Meshtastic/Helpers/Mqtt/MqttClientProxyManager.swift
> Added ssl support and address:port parsing logic

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Enums/HardwareModels.swift
- Meshtastic/Enums/LoraConfigEnums.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/Mqtt/MqttClientProxyManager.swift
- Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion
- Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV15.xcdatamodel/contents
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Nodes/DeviceMetricsLog.swift
- Meshtastic/Views/Nodes/EnvironmentMetricsLog.swift
- Meshtastic/Views/Nodes/NodeList.swift
- Meshtastic/Views/Nodes/RemoteHardware.swift
- Meshtastic/Views/Settings/Config/Module/MQTTConfig.swift
- Meshtastic/Views/Settings/Config/PositionConfig.swift
- de.lproj/Localizable.strings
- en.lproj/Localizable.strings
- zh-Hans.lproj/Localizable.strings
> Setup MQTT client proxy connection

- Meshtastic/Helpers/BLEManager.swift
This implements notifications when a device preferred disconnects without the users knowledge
> Closes #271

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Extensions/Measurement.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Nodes/Helpers/Map/NodeMapSwiftUI.swift
- Meshtastic/Views/Nodes/Helpers/Map/PositionAltitudeChart.swift
- Meshtastic/Views/Nodes/Helpers/NodeListItem.swift
- Meshtastic/Views/Nodes/MeshMap.swift
* Only store the latest position if it is the same as the previous position
* Add Elevation graph to the map view
* Improve node map camera position
* Show detection sensor icon pin on the mesh map
> 2.2.12 working changes

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Export/WriteCsvFile.swift
- Meshtastic/Extensions/CoreData/NodeInfoEntityExtension.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Views/Nodes/DeviceMetricsLog.swift
- Meshtastic/Views/Settings/About.swift
- Meshtastic/Views/Settings/Channels.swift
- Meshtastic/Views/Settings/Config/Module/StoreForward.swift
- Meshtastic/Views/Settings/Firmware.swift
- Meshtastic/Views/Settings/FirmwareApi.swift
- Meshtastic/Views/Settings/RouteRecorder.swift
- Meshtastic/Views/Settings/Routes.swift
- Meshtastic/Views/Settings/Settings.swift
* Pull firmware hardware details from json api
* pull firmware releases from json api
> 2.2.19 Working Changes

- Meshtastic/Views/Settings/Firmware.swift
Send Reboot OTA admin message to S3 devices
> Send Reboot OTA admin message to S3 devices

- Meshtastic/Persistence/UpdateCoreData.swift
- de.lproj/Localizable.strings
- en.lproj/Localizable.strings
- zh-Hans.lproj/Localizable.strings
> trivial spelling corrections to logged messages

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/RetryButton.swift
- Meshtastic/Views/Messages/UserMessageList.swift
Implements a simple retry mechanism similar to iMessages.
Closes https://github.com/meshtastic/Meshtastic-Apple/issues/456
> feature: add simple retry mechanism

- Meshtastic/Extensions/Float.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Settings/Settings.swift
…ring the database with less crashing
> 2.2.23 Working Changes II

- Meshtastic/Views/Settings/Channels.swift
* Don't show initial key load as invalid unless it is invalid
* remove green around valid key
* Add some padding
* Show larger keys on multiple lines
> Channel key editor

- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/RetryButton.swift
- Meshtastic/Views/Messages/UserMessageList.swift
Fixes bug reported here: https://github.com/meshtastic/Meshtastic-Apple/pull/486#issuecomment-1954696143
> fix: channel message retry not updating ack state

- Meshtastic/Extensions/UserDefaults.swift
> UserDefaults extension

- Meshtastic/Enums/AppSettingsEnums.swift
- Meshtastic/Extensions/UserDefaults.swift
- Meshtastic/Views/Settings/Config/Module/DetectionSensorConfig.swift
I tested this and it's not crashing. 
The enums are stored as rawValues 
to restore them the enum needs to be Decodable and the compiler will complain is they are not so it's compiler safe
I'm then turning the stored value into Json for decoding...
> Fixing UserDefault wrapper crashing with enums

- Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift
- Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift
…ils.  Don't show the delete waypoint button if you are not conneced to a node
> Hide waypoint button when not connected

- Meshtastic/Views/Settings/Firmware.swift
> Closes #618

- Meshtastic/Extensions/Logger.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Messages/Messages.swift
- Meshtastic/Views/Settings/Config/Module/PaxCounterConfig.swift
- Meshtastic/Views/Settings/Config/PowerConfig.swift
A few warning fixes; and a few more logs
> misc fixes

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Extensions/Url.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/Mqtt/MqttClientProxyManager.swift
- Meshtastic/Persistence/Persistence.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Settings/AppData.swift
- Meshtastic/Views/Settings/AppSettings.swift
- Meshtastic/Views/Settings/Config/PositionConfig.swift
- Meshtastic/Views/Settings/Settings.swift
> Backup database functionality

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/CommonRegex.swift
Not my finest code. Just formatting things like the legacy characteristic and sending it through the same extracted method
> New BLE LogRecord characteristic

- Localizable.xcstrings
- Meshtastic/Views/Settings/Channels.swift
- Meshtastic/Views/Settings/SaveChannelQRCode.swift
- Meshtastic/Views/Settings/ShareChannels.swift
* Fix disable channel crash if you disable more than one channel
* use a switch to make generate qr code more readable
> Fix disable channel crash

- Localizable.xcstrings
- Meshtastic.xcodeproj/xcshareddata/xcschemes/WidgetsExtension.xcscheme
- README.md
- scripts/gen_protos.sh
This change bumps the protobufs, and fixes a small issue in the script where the git submodules were not updating when the script was run.
> Bump Protos

- Localizable.xcstrings
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
- Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift
This change redesigns the node detail screen!
I tried the redesigned screen side by side with the old one, and made sure the new UI has feature parity with the old one. I also ran the mac app on my dev machine, and validated it worked there.
| Before | After |
| ------------- | ------------- |
| ![Watch the video](https://github.com/meshtastic/Meshtastic-Apple/assets/17112724/1c75dfac-018b-4f68-9561-786cfdd556b8) | ![Watch the video](https://github.com/meshtastic/Meshtastic-Apple/assets/17112724/9c4c7862-5a25-4021-a88a-438a293babd5) |
> Node Detail Screen Redesign

- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Allow Node Number, User Id, and Uptime to be selected.
> Copyable text in Node Detail

- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
This was leftover from the node actions refactor and can be deleted
> Delete dead code from node detail

- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
> Add device role to node details

- Localizable.xcstrings
- Meshtastic/Views/Nodes/Helpers/Actions/DeleteNodeButton.swift
- Meshtastic/Views/Nodes/NodeList.swift
Dont allow deleting the connected node
Hide 3 context menu items that need refactoring.
> Delete Button Cleanup

- .github/pull_request_template.md
- CONTRIBUTING.md
- Meshtastic.xcodeproj/xcshareddata/xcschemes/WidgetsExtension.xcscheme
- MeshtasticProtobufs/Sources/meshtastic/apponly.pb.swift
- MeshtasticProtobufs/Sources/meshtastic/config.pb.swift
- MeshtasticProtobufs/Sources/meshtastic/mesh.pb.swift
- MeshtasticProtobufs/Sources/meshtastic/module_config.pb.swift
- MeshtasticProtobufs/Sources/meshtastic/telemetry.pb.swift
- README.md
- RELEASING.md
- scripts/create-release-branch.sh
This change institutes several new development lifecycle changes across the project. The major changes are outlined below.
* Start using trunk-based development by encouraging contributors to target main with their changes.
* Formalize a release process by documenting the steps for managing released versions on GitHub.
* Adds a PR template so that pull requests follow a standardized format
This is a big shift in how things are currently managed, and I wanna make sure we're all good with this before accepting these changes.
> Adding project documentation to formalize development and release management

- Localizable.xcstrings
- Meshtastic/Views/Nodes/DeviceMetricsLog.swift
Select the chart by the second so that the line is by the dots on the chart
> Select the chart by the second

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift
* Remove padding from node hardware battery indicator
* Bump rssi and snr font back up to caption
> Node Details Hardware Section Updates

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic.xcodeproj/xcshareddata/xcschemes/WidgetsExtension.xcscheme
- Meshtastic.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Meshtastic/AppIntents/MessageChannelIntent.swift
- Meshtastic/AppIntents/SendWaypointIntent.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/MeshtasticApp.swift
> App intents closes #33

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/AppIntents/AppIntentErrors.swift
- Meshtastic/AppIntents/MessageChannelIntent.swift
- Meshtastic/AppIntents/NodePositionIntent.swift
- Meshtastic/AppIntents/SendWaypointIntent.swift
Created Error handling and a new Node Position Intent
Better error handling so users know if something went wrong.
Tested on my iPhone
> Created Error handling and a new Node Position Intent

- Meshtastic/Views/Helpers/SecureInput.swift
- Meshtastic/Views/Settings/Config/SecurityConfig.swift
Require 32 byte keys, allow the admin key to be empty
> Validation for Security Keys

- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/UserMessageList.swift
Use scrollTo method available now that 16.6 is required.
> New scroll methods

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Helpers/Weather/LocalWeatherConditions.swift
- Meshtastic/Views/Nodes/EnvironmentMetricsLog.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Add wind metrics to the environment metrics table
Update wind widget on node details
> Wind metrics

- Meshtastic/Views/Helpers/Help/LockLegend.swift
Fix typo reguires -> requires #885
> 885 fix reguires typo -> requires

- Meshtastic/Views/Settings/Channels/ChannelForm.swift
Imprecise locations for the default key
> update channel form

- Localizable.xcstrings
- Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift
> Clean up waypoint form

- Localizable.xcstrings
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Change the text for the key match error a little, remove setting key match to false when pki fails
> Keymatch debugging

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Extensions/CoreData/NodeInfoEntityExtension.swift
- Meshtastic/Extensions/CoreData/TraceRouteEntityExtension.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/LocationsHandler.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion
- Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 45.xcdatamodel/contents
- Meshtastic/Resources/DeviceHardware.json
- Meshtastic/Views/Layouts/TraceRoute.swift
- Meshtastic/Views/Messages/MessageText.swift
- Meshtastic/Views/Nodes/TraceRouteLog.swift
- Meshtastic/Views/Settings/Config/Module/StoreForwardConfig.swift
- Meshtastic/Views/Settings/Logs/LogDetail.swift
> Twoway traceroute

- Meshtastic/Views/Nodes/TraceRouteLog.swift
> Remove testing data

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/AppIntents/SaveChannelSettingsIntent.swift
Added an Intent that takes in a channel URL and saves it to the channel settings.
Allows people to create hotkeys to switch channel settings on the fly.
I tested it on my iPhone.
> Channel URL Intent

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Extensions/CoreData/UserEntityExtension.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion
- Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 47.xcdatamodel/contents
- Meshtastic/Views/Messages/UserList.swift
- Meshtastic/Views/Nodes/Helpers/Actions/IgnoreNodeButton.swift
- Meshtastic/Views/Nodes/Helpers/NodeListFilter.swift
- Meshtastic/Views/Nodes/MeshMap.swift
- Meshtastic/Views/Nodes/NodeList.swift
> Add ignore node functionality

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
Added complete Serbian (100%) language translations to the application's localization system.
To make the application accessible to Serbian-speaking users by providing a fully localized experience. This expansion of language support will help reach more users in the Serbian market and improve the app's international accessibility.
- Manually reviewed all Serbian translations for accuracy and completeness
- Verified that all UI elements properly display Serbian characters
- Tested language switching functionality to/from Serbian
- Checked text formatting and layout with Serbian translations to ensure proper display
- Verified that all dynamic content (like date formats, numbers, etc.) follows Serbian locale conventions
- [] I have commented my code, particularly in complex areas.
- [] I …
> Added Serbian translations

- Localizable.xcstrings
- Meshtastic/Enums/DeviceEnums.swift
- Meshtastic/Enums/DisplayEnums.swift
- Meshtastic/Enums/TelemetryEnums.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Helpers/LoRaSignalStrengthIndicator.swift
- Meshtastic/Views/Helpers/MQTTIcon.swift
- Localized various strings in the `BLEManager.swift`, `MQTTIcon.swift`, and `UpdateCoreData.swift` files.
- Added new localization keys to the `Localizable.strings` file.
- To ensure that the application supports multiple languages on some missing strings and provides a better user experience for non-English speakers.
- To make error messages, notifications, and UI elements translatable.
- Unfortunately I was not able to test yet since I do not have paid developer account
> Localization upgrade on missing strings

- Localizable.xcstrings
- Meshtastic/Enums/LoraConfigEnums.swift
- Localized various strings in the `LoraConfigEnums.swift` file.
- Added new localization keys to the `Localizable.strings` file for region codes and modem presets.
- To ensure that the application supports multiple languages and provides a better user experience for non-English speakers.
- To make error messages, notifications, and UI elements translatable.
> Update lora config translations

- Meshtastic.xcodeproj/project.pbxproj
> Bump version

- Meshtastic/Helpers/MeshPackets.swift
- Fix plumbing of critical bool for textMessagePacket notification
> 2.5.16 changes

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/AppIntents/MessageNodeIntent.swift
> Add Message Node Intent

- Localizable.xcstrings
Updated Chinese translation
Helping Chinese-speaking users around the world
Using the Chinese system
> Updated Chinese translation

- Meshtastic/AppIntents/NavigateToNodeIntent.swift
- Meshtastic/Views/Nodes/Helpers/Actions/NavigateToButton.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
- Meshtastic/Views/Nodes/PositionLog.swift
Added NavigateToNode Intent and navigate to button
Enable easily navigating the position of a node without having to type/copy coordinates.
Tested on my iPhone.
https://github.com/user-attachments/assets/eb65b344-90b6-407d-aaf4-26df323baf9a
https://github.com/user-attachments/assets/ea0b47b3-c627-4688-9509-053091da48b3
> Added NavigateToNode Intent and navigate to button

- Localizable.xcstrings
Synced new changes with Serbian translations for various terms and features.
Serbian translations were updated to ensure accuracy and usability for Serbian-speaking users.
Verified Serbian translations by reviewing the updated terms and ensuring they display correctly in the UI.
N/A
> Sync Serbian translations

- Meshtastic/Views/ContentView.swift
> toolbar background always visible

- Localizable.xcstrings
Translated the interface text to Serbian Cyrillic.
The change was made to accommodate Serbian-speaking users and ensure better accessibility and understanding of the interface.
The translation was reviewed by native Serbian speakers to ensure accuracy and consistency. It was also tested in the user interface to verify that all text elements display correctly.
> Sync Serbian translations 01032k25

- Meshtastic/Views/Messages/ChannelMessageList.swift
> Read all messages when one in the channel is read

- Localizable.xcstrings
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 49.xcdatamodel/contents
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/MessageText.swift
- Meshtastic/Views/Settings/Config/Module/StoreForwardConfig.swift
> Update Store and Forward

- Meshtastic/Views/Settings/Settings.swift
> Fix for External Notification and Serial module settings

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/UserMessageList.swift
- Meshtastic/Views/Nodes/Helpers/ScrollToBottomButton.swift
> Added Back Scroll To Bottom

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/UserMessageList.swift
- Meshtastic/Views/Nodes/Helpers/ScrollToBottomButton.swift
Added back scroll to bottom button.
Tested these changes on my phone with a ton of messages.
https://github.com/user-attachments/assets/99a5928b-1fe3-4757-a909-4a4e08b8ebc2
> Scroll to bottom

- Localizable.xcstrings
I changed a string in the Italian translation
The previous string was incorrect
Not tested
- [] I have commented my code, particularly in complex areas.
- [ x] I have verified whether these changes require an update to existing documentation or if new documentation is needed, and created an issue in the [docs repo](http://github.com/meshtastic/meshtastic/issues) if applicable.
> Fixed italian translation for PWD

- Localizable.xcstrings
- Meshtastic/Extensions/String.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Helpers/BLESignalStrengthIndicator.swift
- Meshtastic/Views/Helpers/BatteryCompact.swift
- Meshtastic/Views/Helpers/BatteryGauge.swift
- Meshtastic/Views/Helpers/ConnectedDevice.swift
- Meshtastic/Views/Messages/TextMessageField/RequestPositionButton.swift
- Meshtastic/Views/Messages/TextMessageField/TextMessageSize.swift
- Meshtastic/Views/Nodes/Helpers/Actions/IgnoreNodeButton.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
- Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift
- Meshtastic/Views/Nodes/Helpers/NodeListItem.swift
- Meshtastic/Views/Nodes/NodeList.swift
Added accessibility tags to a lot of the sections that were hard/impossible to navigate without sight.
After sitting with a Visually impaired user understood the lack of enthusiasm with the Meshtastic radio.
Got the build flow going on macbook and tested on tethered iphone. 
Ensured there are no visual changes and with VoiceOver my visually impaired tester got it all going now.
Tried to stay out of the hair of the ongoing localization efforts.
> Additional accessibilityLabels for VoiceOver users.

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/AppIntents/AddContactIntent.swift
- Meshtastic/Views/Nodes/Helpers/ShareContactQRDialog.swift
> Import Contact App Shortcut and add a share url button to the page

- Localizable.xcstrings
Added new Chinese (Traditional) translations for the recently introduced keys.
> Taiwanese Translation Update

- Localizable.xcstrings
- Meshtastic/Extensions/UserDefaults.swift
- Meshtastic/Tips/BluetoothTips.swift
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/UserMessageList.swift
- Meshtastic/Views/Settings/Config/Module/StoreForwardConfig.swift
Reverts meshtastic/Meshtastic-Apple#1222
> Revert "Update serbian translations"

- Localizable.xcstrings
- Meshtastic/AppIntents/SendWaypointIntent.swift
- Meshtastic/Extensions/CoreData/WaypointEntityExtension.swift
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift
Added a change location to the current option.
Easier to send a quick waypoint from current location.
Cant send a video of it working (it does work) because I will dox myself
> Added a button to change waypoint to your location

- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Added button to copy public key.
No way to access the other node's public key easily for remote admin.
> Added copying public key button

- Localizable.xcstrings
- Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift
> Seperated button

- Meshtastic/Helpers/BLEManager.swift
> Added retry timeout

- Meshtastic/Helpers/BLEManager.swift
> Bump timer back down

- Localizable.xcstrings
Changed some translations for Italian language
Why did it change?
There are some translations that do not make sense in Italian, while for others the translation has been made homogeneous between different texts. Added missing translations.
How is this tested?
Not tested with XCode, but I checked it is a valid json
> Update italian translation

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Enums/KeyBackupStatus.swift
- Meshtastic/Helpers/KeychainHelper.swift
- Meshtastic/Meshtastic.entitlements
- Meshtastic/Views/Settings/Config/SecurityConfig.swift
Backup the private key for a node to your iCloud keychain
> iCloud Keychain Private Key backup

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Enums/KeyBackupStatus.swift
- Meshtastic/Extensions/CoreData/UserEntityExtension.swift
- Meshtastic/Helpers/KeychainHelper.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Meshtastic.entitlements
- Meshtastic/MeshtasticApp.swift
- Meshtastic/Persistence/UpdateCoreData.swift
- Meshtastic/Views/Helpers/Help/ChannelsHelp.swift
- Meshtastic/Views/Messages/ChannelList.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
- Meshtastic/Views/Settings/Channels.swift
- Meshtastic/Views/Settings/Config/SecurityConfig.swift
- Meshtastic/Views/Settings/ShareChannels.swift
* Key Generation Updates
* User ID Generation fixes
> 2.6.8 Working Changes

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/MeshtasticApp.swift
- Meshtastic/Tips/PersistantTips.swift
- Meshtastic/Views/Bluetooth/Connect.swift
- Meshtastic/Views/Messages/Messages.swift
- Meshtastic/Views/Settings/AppSettings.swift
- Meshtastic/Views/Settings/Settings.swift
Remove the x from the three persistent tips and allow the 2 channel tips to be closed again
> Persistent tips

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Helpers/BLEManager.swift
- Meshtastic/Views/Helpers/ChannelLock.swift
- Meshtastic/Views/Helpers/Help/ChannelsHelp.swift
- Meshtastic/Views/Messages/ChannelList.swift
- Meshtastic/Views/Settings/Channels.swift
- Meshtastic/Views/Settings/ShareChannels.swift
* Update channel lock icons to only be red when sending private locations unencrypted.
* Update channel help
* Add channel help to channel settings page
> 2.6.9 Working Changes

- Meshtastic/Helpers/BLEManager.swift
Fixes some potential crash points for BLE devices out of range or firmware crashes
> Remove nodenum assumptions

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
I added the Japanese translation
Because the Japanese translation was not set
Check each items
> Added Japanese translation

- Meshtastic/Views/Settings/UserConfig.swift
Show save button when unmessagable changes
> Show save button when unmessagable changes

- Meshtastic/Extensions/Bundle.swift
- Meshtastic/MeshtasticApp.swift
- Meshtastic/Views/Settings/AppSettings.swift
* Add isTestFlight bundle extension
* Set DataDog environment properly
* Show Autoconnect toggle in app settings for TestFlight and debug
> Add isTestFlight bundle extension, set environments for datadog

- Localizable.xcstrings
- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/AppIntents/MessageNodeIntent.swift
- Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Just had to delete it and re-add it
> Fixed the message node intent

- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/UserMessageList.swift
Attempt #2 seems to be working better
> Remove gotFirstUnreadMessage bool that is breaking things

- Meshtastic/Accessory/Transports/TCP/TCPConnection.swift
Fixes and improvements to the TCP transport:
- If a TCP connection is cancelled during a read operation, it may get into an inconsistent state.
More maybe added to this pull request as I dig further into edge cases.
Prevent inconsistent behavior with cancellation
iOS 26 simulator connected to a TCP node.
> Cancellation handler for receiveData() function

- Meshtastic/Views/Messages/ChannelList.swift
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/Messages.swift
- Meshtastic/Views/Messages/TextMessageField/TextMessageField.swift
- Meshtastic/Views/Messages/UserMessageList.swift
* Remove manual scrolling
* Remove scroll to bottom button
* Add a new function to manage reading messages
* Remove extra NavigationStack
> Remove all problematic scrolling logic in favor of swiftui built in scroll features

- Meshtastic.xcodeproj/project.pbxproj
- Meshtastic/Accessory/Accessory Manager/AccessoryManager+FromRadio.swift
- Meshtastic/Accessory/Accessory Manager/AccessoryManager+ToRadio.swift
- Meshtastic/Helpers/MeshPackets.swift
- Meshtastic/Views/Connect/Connect.swift
- Meshtastic/Views/Helpers/RXTXIndicatorView.swift
- Meshtastic/Views/Messages/ChannelList.swift
- Meshtastic/Views/Messages/ChannelMessageList.swift
- Meshtastic/Views/Messages/TextMessageField/TextMessageField.swift
- Meshtastic/Views/Messages/UserList.swift
- Meshtastic/Views/Nodes/MeshMap.swift
- Meshtastic/Views/Settings/RouteRecorder.swift
- Meshtastic/Views/Settings/Settings.swift
* Build for iOS 26
* Fix Mesh Map Controls Position
* Fix Route Recorder Map Controls Position
* Messaging Performance Improvements
* Fix delete channel and DM messages context menu item bugs
* Update Ringtone config to request the ringtone from the device if external notifications is enabled
> 2.7.1 Working Changes

- Meshtastic/Helpers/MeshPackets.swift
Reverts meshtastic/Meshtastic-Apple#1431
> Revert "Missing message fix, attempt #2"
