Meshtastic/Helpers/Map/OfflineTileManager.swift
The url returned by MKTileOverlay.url(forTilePath:) is subsequently used by MKTileOverlay.loadTile(at:result:) for download. In the case of a tile that was just cached by OfflineTileManager.persistLocally(path:) we now return the local file URL to avoid downloading the remote image twice.
=> fix: map tiles being downloaded remotely twice

Meshtastic/Helpers/Map/OfflineTileManager.swift
Corrects caching to honor zoom range and helps save a bit of network bandwidth, especially when zoomed in past range that the tile server supports (i.e. avoid 404, etc.)
=> fix: don't fetch tiles greater than specified upper bound

Meshtastic/Views/Nodes/NodeMap.swift
Similar to https://github.com/meshtastic/Meshtastic-Apple/pull/475 fixes an issue where map options sheet sizing was inverted when enabling/disabling offline maps.
Before:
https://github.com/meshtastic/Meshtastic-Apple/assets/7528924/a332106a-e59d-4fa7-8381-c02e8d6768c8
After:
https://github.com/meshtastic/Meshtastic-Apple/assets/7528924/964b5b8c-7b50-42ab-b733-a687b384f05a
=> fix: inverted map options sheet resizing

Meshtastic/Helpers/Map/OfflineTileManager.swift, Meshtastic/Helpers/Map/TileOverlay.swift
Previously a map tile cache miss would cause 2x loading of the tile: once from the remote tile server (which is then written to disk) and once from disk during the default `MKTileOverlay.loadTile` function.
Instead we now directly implement `loadTile` so that we can avoid the duplicate loading and simply return the fetched remote tile after it is cached, which leads to a noticeable improvement in offline map performance.
Note: I recommend reviewing per commit, second commit is just some cleanup.
=> improvement: avoid duplicate map tile loading

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Enums/IntervalEnums.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion, Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 27.xcdatamodel/contents, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Settings/Config/BluetoothConfig.swift, Meshtastic/Views/Settings/Config/ConfigHeader.swift, Meshtastic/Views/Settings/Config/DeviceConfig.swift, Meshtastic/Views/Settings/Config/DisplayConfig.swift, Meshtastic/Views/Settings/Config/LoRaConfig.swift, Meshtastic/Views/Settings/Config/Module/AmbientLightingConfig.swift, Meshtastic/Views/Settings/Config/Module/CannedMessagesConfig.swift, Meshtastic/Views/Settings/Config/Module/DetectionSensorConfig.swift, Meshtastic/Views/Settings/Config/Module/ExternalNotificationConfig.swift, Meshtastic/Views/Settings/Config/Module/MQTTConfig.swift, Meshtastic/Views/Settings/Config/Module/RangeTestConfig.swift, Meshtastic/Views/Settings/Config/Module/RtttlConfig.swift, Meshtastic/Views/Settings/Config/Module/SerialConfig.swift, Meshtastic/Views/Settings/Config/Module/StoreForwardConfig.swift, Meshtastic/Views/Settings/Config/Module/TelemetryConfig.swift, Meshtastic/Views/Settings/Config/NetworkConfig.swift, Meshtastic/Views/Settings/Config/PositionConfig.swift, Meshtastic/Views/Settings/Config/PowerConfig.swift, Meshtastic/Views/Settings/Config/SaveConfigButton.swift, Meshtastic/Views/Settings/Settings.swift, en.lproj/Localizable.strings
Adds ability to configure power settings in the app. Also refactors two shared config views to greatly reduce lines of code: `ConfigHeader` and `SaveConfigButton`. I recommend reviewing without whitespace changes visible.
=> feature: add power configuration

.gitignore
The protobufs submodule was not properly tracked in the git index due to it being ignored, resulting in the following error (which is now fixed):
```
error: pathspec 'protobufs' did not match any file(s) known to git
```
By tracking the submodule it is now easier to discover from which version of protobufs the Swift definitions were generated.
=> chore: add protobufs to git index

README.md, gen_protos.sh
I just set up the project for the first time and noticed a couple minor things:
I updated README.md to include a command for initializing the protobufs submodule
I also updated `gen_protos.sh` to check the right directory (`./protobufs`, not `../protobufs`)
Additionally updated the same to echo the git submodule command and added ``` to the second echo
=> Updated readme to include git submodule command and gen_protos.sh to check the directory

Meshtastic/Views/Helpers/ConnectedDevice.swift, Meshtastic/Views/Messages/ChannelMessageList.swift, Meshtastic/Views/Settings/Config/Module/MQTTConfig.swift
First and foremost, please let me know if there are any styling issues with my code, I'm very rusty on iOS code generally and a relative newbie when it comes to SwiftUI.
This PR adds an icon in the channels detail view when uplink or downlink is enabled and also adds the status of the connection in the color of the icon as well.
This also adds the same connection icon in the MQT config settings screen
Here are some screenshots:
=> Add mqtt status icon in channels with uplink/downlink enabled

Meshtastic/Views/Helpers/LoRaSignalStrengthIndicator.swift
I'm guessing a bit, but I suspect this was the intent, but the inequalities are backwards (as clearly no number is both greater than -115 and less than -120).
This should make it so higher than -115 is green, -115 to -120 is yellow, -120 to -125 is orange, and below that is red.
=> Make yellow/Fair RSSI possible

Meshtastic/Views/Bluetooth/Connect.swift, Meshtastic/Views/Messages/ChannelMessageList.swift
The MQTT indicator was always showing connected on all channels, fixed that
Also added/fixed the connect screen so the indicator both shows the current connection status as well as the current topic
=> Fix bug where MQTT was showing connected even if down/up was not enabled

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Extensions/UserDefaults.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Bluetooth/Connect.swift, Meshtastic/Views/Messages/MessageContextMenuItems.swift, Meshtastic/Views/Messages/TextMessageField/TextMessageField.swift, Meshtastic/Views/Nodes/DeviceMetricsLog.swift, Meshtastic/Views/Settings/AppSettings.swift, Meshtastic/Views/Settings/Channels.swift, Meshtastic/Views/Settings/Config/DeviceConfig.swift, Meshtastic/Views/Settings/Firmware.swift, Meshtastic/Views/Settings/RouteRecorder.swift
*  Fix device metrics grid column sizing
* Show alert bell button on direct messages
* Fix some crashes
* Add power off to connect context menu
* Add hops away to message details, clean up RSSI and SNR visibility
* Set provide location default to 30 seconds
* Only delete routes on factory reset and clear app data
* Close route recorder modal when finished
=> 2.3.6 working changes

Meshtastic/Export/LogDocument.swift, Meshtastic/Helpers/MeshLogger.swift, Meshtastic/Views/Messages/Messages.swift, Meshtastic/Views/Nodes/Helpers/Map/MapContent/MeshMapContent.swift, Meshtastic/Views/Settings/Routes.swift
This change addresses a few lint warnings and removes an unresolved closure parameter. 
While fixing the warning in `Route.swift`, I've also cleaned up the way that Lat / Long were handled with a -1 sentinel value, and converted those local variables to `Optional`s
=> Fix Lint & Compiler Warnings

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Views/Nodes/Helpers/Map/NodeMapSwiftUI.swift
This change breaks down `NodeMapSwiftUI.swift` into computed properties to improve compile performance, and adds warnings to the project when a type-check exceeds 200ms.
These stats were from a 2019 Macbook Pro. I expect it'll be much faster on some more recent ARM hardware.
The goal here isn't entirely to optimize for compile performance. Instead, I'm using this statistic as a rough indicator as to which View hierarchies are overly complex and could use some TLC
Compiled & ran the app on a simulator, but haven't been able to build to a device due to entitlements issues.
=> Refactor `NodeMapSwiftUI.swift`

Meshtastic/Helpers/MeshPackets.swift
In some cases, the MQTT status of a node was not being persisted correctly, which could cause confusion when viewing the node list
=> Fix MQTT data inconsistency

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Extensions/CoreData/PositionEntityExtension.swift, Meshtastic/Extensions/CoreData/UserEntityExtension.swift, Meshtastic/Extensions/Protobufs/NodeInfoExtensions.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Persistence/UpdateCoreData.swift
This change extracts several repeated segments of code that map the fields in a mesh packet onto a CoreData model into convenience initializers on the CoreData models. 
By using these new convenience initializers, the field mapping is only done in one place, and can prevent a developer from accidentally missing a field when persisting data.
I ran a debug build on an iPhone 15 Pro Max connected to a Heltec V3, and hooked up MQTT. I was able to detect another local node (mine) and many more over MQTT. I let the app run for a while, and continue to populate the node list over MQTT.
I noticed that some of the "LoRa" nodes weren't actually detected via my radio, so I'm thinking there is another underlying issue about where and how that field is set.
|  | List | Filter | 
|:-:|:-:|:-:|
| LoRa | …
=> Refactor how packets are parsed and persisted to the data model

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Extensions/CoreData/ChannelEntityExtension.swift, Meshtastic/Extensions/CoreData/DeviceMetadataEntityExtension.swift, Meshtastic/Extensions/CoreData/ExternalNotificationConfigEntityExtension.swift, Meshtastic/Extensions/CoreData/LocationEntityExtension.swift, Meshtastic/Extensions/CoreData/MQTTConfigEntityExtension.swift, Meshtastic/Extensions/CoreData/NodeInfoEntityExtension.swift, Meshtastic/Extensions/CoreData/RangeTestConfigEntityExtension.swift, Meshtastic/Extensions/CoreData/SerialConfigEntityExtension.swift, Meshtastic/Extensions/CoreData/StoreForwardConfigEntityExtension.swift, Meshtastic/Extensions/CoreData/WaypointEntityExtension.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/MapKitMap/Custom/MapViewSwiftUI.swift, Meshtastic/Views/Nodes/MeshMap.swift, Meshtastic/Views/Settings/Channels.swift, Meshtastic/Views/Settings/RouteRecorder.swift, Widgets/Info.plist
This change extracts more CoreData entity updates out into `convenience` initialiers and `update(with:)` methods to keep the packet handing code less cluttered. 
Long term, I'm hoping this enables us to split out the code into modules, so we can get a decent test suite going.
=> Extracting More CoreData Boilerplate Part 1

Meshtastic/Extensions/CoreData/ExternalNotificationConfigEntityExtension.swift
Forgot to call the designated initializer during the refactor
=> Fix CoreData crash

Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 37.xcdatamodel/contents
This change adds a constraint on `UserEntity` `num` field, so that the Contacts list won't populate with duplicate entries.
I have a 2 node mesh where i caused one node to send a bunch of packets by powering off and on repeatedly, and saw that it created several user entities before these changes.
After this change, only one entry shows up in the Messages -> Direct Messages section
=> Fix Contact List Duplicates

Meshtastic/Views/Settings/Config/PositionConfig.swift
Minor typo, comma was in the wrong place, corrected.
=> Fix minor comma typo

Meshtastic/Views/Messages/MessageContextMenuItems.swift
The 'Hops Away' contextual menu item for messages was suffixed with a close bracket and 'dB'.
But hops are not measured in dB.
I believe this is a copy/paste bug.
=> Text formatting fix for Hops Away

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift
This change fixes an issue where the node list would sometimes show "Unknown" for several nodes. This was happening because we were relying on outdated objects from the CoreData object graph.
This change also adds a check for a file path before attempting a backup & restore, since this action could sometimes cause bluetooth devices to never successfully reconnect.
=> Fix Issues With Empty User Information

Meshtastic/Extensions/CoreData/MyInfoEntityExtension.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Settings/Config/DisplayConfig.swift
This change tries to address race conditions that occur when repeatedly pairing and unpairing a node via bluetooth. This was caused by the fetch-update code when persisting a `MyInfoEntity` packet instead of relying on CoreData to do the synchronization and merging.
I also factored out a method that updates the appropriate fields on `connectedPeripheral` whenever packets come in, so the node list & bluetooth screen will render correctly.
I also fixed an inverted condition in the message validation logic. We want to make sure messages are _NOT_ empty before we allow them to be sent.
=> Fix MyInfo persistence that caused bluetooth desyncs

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Persistence/QueryCoreData.swift, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Bluetooth/Connect.swift, Meshtastic/Views/Messages/Messages.swift
This change uses the generated API for constructing fetch requests instead of `NSFetchRequest(entityName: "...")`. This avoids unnecessary typecasts and guards.
=> Refactor `NSFetchRequest(entityName:)` to `Entity.fetchRequest()` for type safety

Meshtastic/Views/Settings/Settings.swift
It does not show a Duty Cycle warning when in licensed mode.
I have not tested this by recreating the issue but the build works perfectly.
=> Fixes #714

MeshtasticProtobufs/Sources/meshtastic/config.pb.swift, MeshtasticProtobufs/Sources/meshtastic/powermon.pb.swift, scripts/gen_protos.sh
Update protobufs to the latest. Also, fixed a few issues in the gen_protos.sh script.
=> Bump Protos

Meshtastic/Views/MapKitMap/Custom/LocalMBTileOverlay.swift
On Sonoma these items were throwing errors in Xcode cloud and in Xcode 16 beta, made the suggested changes to fix the build both places
=> add now missing value label

Localizable.xcstrings, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Helpers/LastHeardText.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
This change adds the last heard date to the node details screen. Unfortunately, it seems much of this data is buggy for me, and I have several nodes with lastHeard dates on Jan 1 1970, so I can't really validate that the change works on the happy path.
=> Add First Heard and Last Heard times to node details

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Nodes/NodeList.swift, MeshtasticProtobufs/Sources/meshtastic/apponly.pb.swift, MeshtasticProtobufs/Sources/meshtastic/config.pb.swift, MeshtasticProtobufs/Sources/meshtastic/mesh.pb.swift, MeshtasticProtobufs/Sources/meshtastic/module_config.pb.swift, MeshtasticProtobufs/Sources/meshtastic/telemetry.pb.swift
This change restores the Exchange Positions & Trace Route buttons back in the node list's context menu.
Unfortunately, the context menu doesn't render the alerts after a position packet is sent because the view is already removed from the render. It would take some refactoring to restore that to the node list, but the position packet and traceroute is still sent, and this should be functional enough for now.
Longer term, it would be cool to use a non-blocking UI action sheet-type of toast message for a lot of these confirmation dialog things.
=> Restore the Exchange Positions and TraceRoute button back to the node list context menu

README.md, scripts/hooks/pre-commit, scripts/lint/lint-fix-changes.sh, scripts/setup-hooks.sh
This change adds a few scripts that will automatically set up a `pre-commit` hook to run `swiftlint --fix` on changed files. This will help keep the project's codebase cleaner, and remove a bunch of noise around the more pesky lint errors.
Please test this out on your own machines to help catch any edge cases.
1. Run `./scripts/setup-hooks.sh`
2. Make some changes & commit them.
3. ???
4. Profit
If you need to revert the changes to your local machine from this PR, run this
```
rm .git/hooks/pre-commit
```
=> Adding scripts to setup linting as a pre-commit hook

Meshtastic/Helpers/BLEManager.swift
dont add them as a node in the app
=> Identify repeaters in trace routes

Localizable.xcstrings, Meshtastic/Views/Nodes/DeviceMetricsLog.swift
Allows for chart selection from both the table below the chart and the chart itself.
There is an annotation that I commented out, not sure what it would display here.
@RCGV1 I got the start of some interactivity going.
=> Add interactive selection line to device metrics chart

Meshtastic.xcodeproj/project.pbxproj, Meshtastic.xcworkspace/xcshareddata/swiftpm/Package.resolved, Meshtastic/Extensions/CoreData/ChannelEntityExtension.swift, Meshtastic/Extensions/CoreData/MessageEntityExtension.swift, Meshtastic/Extensions/CoreData/MyInfoEntityExtension.swift, Meshtastic/Extensions/CoreData/UserEntityExtension.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion, Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 41.xcdatamodel/contents, Meshtastic/Persistence/QueryCoreData.swift, Meshtastic/Views/Messages/TapbackResponses.swift, Meshtastic/Views/Settings/Firmware.swift
cleaned up from https://github.com/meshtastic/Meshtastic-Apple/pull/824 which included merge commits & app icon updates
@ChrDel-2 and @garthvh are the original authors of the changes
=> Remove Fetched Properties from channel and message models

Localizable.xcstrings, Meshtastic/Extensions/UserDefaults.swift, Meshtastic/MeshtasticApp.swift, Meshtastic/Views/MapKitMap/Custom/MapViewSwiftUI.swift, Meshtastic/Views/Nodes/NodeMap.swift
The mbtiles functionality is not working and the MapKit map will be removed in the fall anyways so removing this broken functionality. It actually seems to work with an updated mbtiles file, but this whole configuration is hardly used and too complex anyways.
=> Remove broken MB tiles funcitionality

Meshtastic/Extensions/CoreData/ChannelEntityExtension.swift, Meshtastic/Extensions/CoreData/MessageEntityExtension.swift, Meshtastic/Extensions/CoreData/MyInfoEntityExtension.swift, Meshtastic/Extensions/CoreData/UserEntityExtension.swift
I can't replicate it, but there is not an explicit sort by message timestamp and there have been a couple of reports of out of order messages since the change from fetched properties (which also lacked a default sort from what I can tell)
This seems to be the same order I get by default without the sort descriptors so it does not seem very risky.
=> Sort Descriptors for Message Extensions

Localizable.xcstrings, Meshtastic/Views/Nodes/Helpers/Actions/ExchangePositionsButton.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/NodeList.swift
While a little ugly right now this is the right logic / flow for the node list context menu items and node details actions
=> Node List / Details Context Menu Items and Actions Logic

Meshtastic/Extensions/CoreData/ChannelEntityExtension.swift, Meshtastic/Extensions/CoreData/MyInfoEntityExtension.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Views/ContentView.swift, Meshtastic/Views/Nodes/NodeList.swift, Meshtastic/Views/Settings/Routes.swift
Use RX time for messages unless it is off by more than 10 seconds in either direction and then use the current time from the phone to prevent bad times in the past or future from affecting message sort.
Everything else will continue to use RX time and NSOrderedSets
=> 0 Message Time Logic

Meshtastic/Helpers/MeshPackets.swift
Refactor caused low battery notifications to be sent for every node but the connected one
=> Only send battery nofifications from the local node

Meshtastic/Router/NavigationState.swift, Meshtastic/Router/Router.swift, Meshtastic/Views/ContentView.swift, Meshtastic/Views/Messages/Messages.swift, Meshtastic/Views/Nodes/MeshMap.swift, Meshtastic/Views/Nodes/NodeList.swift, Meshtastic/Views/Settings/Settings.swift, MeshtasticTests/RouterTests.swift
This change modifies `NavigationState` to separately track the tab's selection behavior from the selected tab. 
This should prevent the issue where switching back & forth between messages / other tabs on a phone will leave the app showing the "Select a conversation" screen. This also simplified the `Binding`s across the root screens for each tab.
=> Refactor router state to more closely match tab bar behavior

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Helpers/BLEManager.swift
Use position source on position packets sent from the phone to the node
=> set position source

Meshtastic/Helpers/BLEManager.swift
Set the to to the current node
=> set time source properly

Localizable.xcstrings, Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Added a link to the waypoint details view to drop the waypoint as a pin in maps
=> Waypointform drop maps pin

Meshtastic.xcworkspace/xcshareddata/swiftpm/Package.resolved, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/LocalNotificationManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/MeshtasticAppDelegate.swift
Creates Actionable notifications for DMs and channel messages. Includes thumbs down/up tapbacks and reply.
Useful for quite responses and watch OS.
on my iPhone
=> Actionable Notifications

Meshtastic/Views/Helpers/LoRaSignalStrengthIndicator.swift
Fixed incorrect signal quality caculations when RSSI was not present. (this is common because NodeInfo does not store RSSI)
Hide RSSI when value is 0 (unknown).
https://github.com/meshtastic/Meshtastic-Apple/issues/930
UI was showing misleading signal quality metrics.
=> fix signal quality display when rssi missing

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Messages/MessageText.swift
* Show DM lock Indicator on received messges
* Show client notifications
=> Dm lock indicator

Meshtastic/Helpers/BLEManager.swift
This change sets timestamps in the TraceRoute data structure. Missing timestamps in
the TraceRouteEntity was causing CoreData exceptions, resulting in multi-hop traceroutes
not showing up in the App. 
The App was throwing an exception because the time field is required and was not always getting
set.
I ran this on my phone against a number of nodes in the area which can result in a variety of routes
and direct responses.
=> Add missing timestamps to TraceRoute data structures

Meshtastic/Views/Settings/Config/PositionConfig.swift
Added .onChange to Position Flag toggles to enable the save button when these values are changed.
Changing these toggles was not enabling the save button. 
Ran through various iterations of modifying the Position Flag and Advanced Position Flags toggles to verify that the save button was enabled. Also saved configuration changes to ensure that the configuration was being successfully saved.
=> Enable Save button when position flags are modified

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Nodes/TraceRouteLog.swift
This change updates traceroute handling of SNR values.
1. For direct traceroute results, use the SNR from the routing message, rather than pulling it from the node entry. Pulling from the node entry causes every direct traceroute entry to show the current SNR for the node, rather than the SNR at the time of the traceroute
2. cleans up a couple spots where the SNR is divided by 4. The change casts them to Floats first then divides so that the decimals aren't truncated.
3. Clean up some incorrect snr checks against 0. SNR can be negative. An unknown SNR is represented as -32. When the SNR value is encoded as an int in the routing message, the value is -128.
4. Fix up some formatting issues with the routeString and routeBackString
These changes clean up some areas which were returning …
=> Traceroute SNR cleanup

Meshtastic/Enums/AppSettingsEnums.swift
Add some shorter distance options to the filtering. This adds options for 2, 5, 10 and 25 miles.
For areas with a dense collection of nodes, such as urban areas, filtering distances of shorter then 50 miles is very helpful. 
Selecting various distances 2, 5, 10, 25, and further to verify that the correct nodes are displayed. Tested with Node List and Mesh Map
=> Add shorter distance options to distance filtering

Meshtastic/Views/Nodes/TraceRouteLog.swift
This change removes the explicit sizing in the traceroute log view, allowing the view to manage the size.
When the traceroute list gets long enough it can push the selected node off the bottom of the screen.
With the explicit min/max heights removed, the view will split the screen between the list and the selected node view.
Looks like this changed behavior with this commit https://github.com/meshtastic/Meshtastic-Apple/commit/f7630262039e697bbe0449bf3ebe9e2a4b092a69. An operator precedence issue was addressed, which exposed this issue. Prior to this change the frame minHeight was not being multiplied as intended, and remained too small to have an impact. 
Ran tests with varying sized traceroute lists and varying screen sizes.
Here's an example of the current behavior with a long list. …
=> Fix View issue when node traceroute list gets long

Meshtastic/Helpers/LocalNotificationManager.swift, Meshtastic/Helpers/MeshPackets.swift
Now provides notifications when unknown nodes send a channel message. Also, schedule all local notifications immediately instead of on a 1-second delay.
Often time-sensitive notifications from nodes could be missed because their node had not yet exchanged node info. This is a bad pattern to just ignore all unknown nodes. Also delaying notifications by 1 second could lead to pile-ups for notifications all spaced out by 1 second. And message notifications came in at a delay.
I tested it on my iPhone and can confirm that the unknown node's notifications work and notifications are being delivered immediately with no issues. Also confirmed that notification actions work.
=> Fixes #1007

Meshtastic/Helpers/LocalNotificationManager.swift, Meshtastic/Helpers/MeshPackets.swift
Remove 1 second trigger from local notifs
Notifications will be scheduled immediately to prevent delays
Tested on my iPhone and apple watch
=> Make notifications instant

Meshtastic/Views/Settings/Config/LoRaConfig.swift
Edit descriptive text to clarify (1) device frequency is calculated based on slot number and other fields, (2) device has a single operating frequency.
Short-time listener, first-time caller.  Please feel free to ignore/reject.
Based on [discussion regarding primary private channels](https://www.reddit.com/r/meshtastic/comments/1howp8k/frequency_slot_changes/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) in r/Meshtastic
I thought it might help if user guidance pulled in a little more from these resources.
- https://meshtastic.org/docs/configuration/tips/#creating-a-private-primary-with-default-secondary
- https://meshtastic.org/docs/overview/radio-settings/#frequency-slot-calculator
String edit only.
=> Update frequency slot description in Settings >> LoRa

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Nodes/TraceRouteLog.swift
Fixed issue where traceroute info wasn't saved if route back wasn't valid.
Update route back handling to display "unknown" when the route back info is not valid.
Looks like the traceroute data could get dropped if the route back isn't valid. With that fixed, the route back could display "Direct" when the route back data is invalid which is incorrect.
Looking for feedback. The other option is that we just drop references to back messages. But I thought this was a little more clear that the route back data is invalid.
Ran various traceroutes and validated the data. I. don't have a setup that will return invalid route back info, so I tested that by artificially dropping the route back processing.
Here's an example of what the message will look like if the route back data is invalid.
=> Update traceroute back route display to handle case where route back is not valid

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Export/WriteCsvFile.swift, Meshtastic/Extensions/CoreData/NodeInfoEntityExtension.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Meshtastic.xcdatamodeld/.xccurrentversion, Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 49.xcdatamodel/contents, Meshtastic/Views/Helpers/PowerMetrics.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/PowerMetricsLog.swift, Meshtastic/Views/Settings/Config/Module/MQTTConfig.swift
Added power metrics in the main node detail screen, added power metrics icon in node list, added charts for power metric details with clear/save
Addresses #811
=> Add power metrics

Meshtastic/Info.plist
This is displayed during first-time setup as the app requests permissions, so it's high-profile.
=> Fix spelling of "coordinates"

Meshtastic/Helpers/BLEManager.swift
Adds a notification for completed traceroutes. The notification includes the routeText and the routeBackText seen in the TR log, as well as as hop from and hop back value
Right now, it's hard to know when a TR has been completed
Run a TR on a node, wait for it to complete, see the notification
=> send tr received notification

Meshtastic/Views/Messages/ChannelMessageList.swift
Added an async function with debounce to handle the read message.
With a large amount of messages in a channel, scrolling would be very laggy.
Tested on one iPhone with my fix and another iPhone without it. I sent around 33 messages to test what would happen.
Before Fix:
https://github.com/user-attachments/assets/73fd8316-3d4b-42c2-8ed9-d269b81d3bf6
After Fix:
https://github.com/user-attachments/assets/47fb9512-3c4f-44f0-a380-3c001bbdc3d4
=> Fixes channel message mark as read lagging the channel message list view

Meshtastic/Views/Messages/ChannelMessageList.swift
Added an async function with debounce to handle the read message.
With a large amount of messages in a channel, scrolling would be very laggy.
Tested on one iPhone with my fix and another iPhone without it. I sent around 33 messages to test what would happen.
Before Fix:
https://github.com/user-attachments/assets/73fd8316-3d4b-42c2-8ed9-d269b81d3bf6
After Fix:
https://github.com/user-attachments/assets/47fb9512-3c4f-44f0-a380-3c001bbdc3d4
=> Fix read indicator

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Export/WriteCsvFile.swift, Meshtastic/Extensions/Constants.swift, Meshtastic/Extensions/CoreData/ManagedAttributePropertyWrapper.swift, Meshtastic/Extensions/CoreData/NodeInfoEntityExtension.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 49.xcdatamodel/contents, Meshtastic/Model/CoreData/TelemetryEntity+CoreDataClass.swift, Meshtastic/Model/CoreData/TelemetryEntity+CoreDataProperties.swift, Meshtastic/Model/Metrics Visualization/MetricTableColumn.swift, Meshtastic/Model/Metrics Visualization/MetricsChartSeries.swift, Meshtastic/Model/Metrics Visualization/MetricsColumnList.swift, Meshtastic/Views/Helpers/BatteryCompact.swift, Meshtastic/Views/Helpers/PowerMetrics.swift, Meshtastic/Views/Helpers/Weather/LocalWeatherConditions.swift, Meshtastic/Views/Messages/ChannelMessageList.swift, Meshtastic/Views/Nodes/DeviceMetricsLog.swift, Meshtastic/Views/Nodes/EnvironmentMetricsLog.swift, Meshtastic/Views/Nodes/Helpers/Metrics Columns/EnviornmentDefaultSeries.swift, Meshtastic/Views/Nodes/Helpers/Metrics Columns/EnvironmentDefaultColumns.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/PowerMetricsLog.swift, Widgets/MeshActivityAttributes.swift, Widgets/WidgetsLiveActivity.swift
Better support for nil values in Environment Metrics
The ability to differentiate nil values from zeros in Metrics was implemented as follows:
- Codegen for TelemetryEntity was disabled (Manual/none). Manual implementations were provided in TelemetryEntity+CoreDataClass and TelemetryEntity+CoreDataProperties
- A ManagedAttribute property wrapper was created to handle the translation of NSNumbers to scalar optionals.
- TelemetryEntity+CoreDataClass is the manual NSManagedObject class implementation that uses the before mentioned @ManagedAttribute to implement scalar optional accessors for various metrics attributes.
- TelemetryEntity+CoreDataProperties is the manual NSManagedObject extension that contains standard @NSManaged implementations
- MeshPackets.swift was updated to load nil …
=> Optional values for TelemetryEntity attributes

Meshtastic/Extensions/String.swift, Meshtastic/Views/Settings/UserConfig.swift
The iOS keyboard appends Unicode 'variation selectors' (extra bytes) to some characters.  This will cause the validation on the shortName field to block using these emojis because they appear as too many bytes. 
This pull request will filter out the variation selectors from the shortName field allowing more emoji to be used in short names.
Some, but not all emoji have 2 presentations.  A colored graphical representation (❤️ ) and a black and white representation (♥).  The unicode standard defines additional bytes, called "variation selectors" that allow you to select the variant you want.
In the case of short name, we probably don't care.  When the variation selector is not provided, [the default is the emoji style](https://en.wikipedia.org/wiki/Emoticons_(Unicode_block)#Variant_forms). …
=> Filter variation selectors from Short Name field

Localizable.xcstrings, Meshtastic/Meshtastic.xcdatamodeld/MeshtasticDataModelV 50.xcdatamodel/contents, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Settings/Config/NetworkConfig.swift
- Added UDP broadcast to network configuration 
- Setting will appear when node supports Wifi or Ethernet
- Database field added in v50 of the CoreData database (Part of 2.5.21) 
- 
UDP broadcast was recently added to firmware
- using a node running 2.6 - setting is persisted via the firmware
=> Add UDP Broadcast setting to Network config

Meshtastic/Views/Helpers/SecureInput.swift
One button does not trigger all the fields anymore.
see https://stackoverflow.com/questions/72163289/swiftui-picker-and-buttons-inside-same-form-section-are-triggered-by-the-same-us
It was a bug
Briefly
=> SecureInput fix: multiple buttons in form triggered by one tap

Meshtastic/Views/ContentView.swift
I fixed the swift ui glitch where the tab bar goes transparent.
Used this as the reference https://developer.apple.com/forums/thread/690563
Very annoying for users and a visual bug.
Tested by using Jason's method to make it transparent
=> Fixed transparent tab view

Meshtastic/Views/Helpers/CircleText.swift, Meshtastic/Views/Messages/ChannelMessageList.swift, Meshtastic/Views/Nodes/Helpers/Map/PositionPopover.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/NodeList.swift
Added clickable node circles to the channel message list and the position popover.
The ability to quickly get in-depth data about a node without having to search for the node in node info tab is very useful.
I tested it on my iPhone.
https://github.com/user-attachments/assets/d692dcd5-d4f9-4377-a18a-48c96df9eeef
https://github.com/user-attachments/assets/6fac45dc-ed52-4ce0-8ae5-49af9faba276
=> Clickable node circles that redirect to node info

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/AppIntents/DisconnectNodeIntent.swift, Meshtastic/AppIntents/ShortcutsProvider.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Bluetooth/Connect.swift
Add animation to demo swipe to disconnect on first connection.
Users do not understand that it is possible to swipe left on a node, this brings it to their attention more prominently.
Tested on my iPhone.
https://github.com/user-attachments/assets/0b11dee2-6273-4e22-8a51-02ee8a2435fc
=> Add animation to demo swipe to disconnect

Localizable.xcstrings, Meshtastic/Helpers/BLEManager.swift
Corrected typo "unders" to "under" in an English localization string related to Bluetooth connection errors.
To fix a grammatical error in the user-facing message.
Verified the string change directly in the English localization file.
N/A
=> Fix: Correct typo in English Bluetooth error message string

Meshtastic/Enums/DeviceEnums.swift
changing `corePortnums` to the correct value in DeviceEnums.swift
adding `none` to the case
Mentioned in #1197 
Tested with my two devices and now works as intended.
=> Updating DeviceEnums.swift

Localizable.xcstrings, Meshtastic/Enums/DeviceEnums.swift
Localization was missing for the Rebroadcast Modes descriptions under Settings/Device. This update adds `.localized` to the relevant strings.
Translation keys were missing.
Built without issues.
=> Add Localization for Rebroadcast Modes Descriptions

Meshtastic/Extensions/UserDefaults.swift, Meshtastic/Views/Nodes/Helpers/Map/MapContent/MeshMapContent.swift, Meshtastic/Views/Nodes/Helpers/Map/MapContent/NodeMapContent.swift, Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift
I set all default occurrences of enableMapWaypoints to be true. I also made it so that any unsent waypoints made during the creation process are deleted if a user cancels or leaves the screen.
There was a discrepancy in the state of enableMapWaypoints (reported in #1081 ), which caused the toggle switch to be on for waypoints but the actual state to be off, so by default, waypoints would not show up on the mesh map. Also, when creating waypoints but never sending them and cancelling or dismissing the view, a permanent waypoint would show up that was never sent to the mesh and cannot be removed.
Tested on two iPhones one with and one without the fix.
Before the Fix:
https://github.com/user-attachments/assets/18bd69ea-ffab-488f-92b8-09a8f83afeaa …
=> Fixed waypoints popup form

Meshtastic/Helpers/BLEManager.swift, Meshtastic/MeshtasticAppDelegate.swift, Meshtastic/Views/Nodes/NodeList.swift
When clicking on a completed TraceRoute notification, the app now navigates to the correct destination node instead of the connected node. This fixes issue #1115 where the app was navigating to the wrong node detail screen.
Fir for issue #1115 
Point at the traceroute destination rather than source node and force GUI updates such that this mechanism works more than once (observed during testing without).
On a tethered phone
- [X ] My code adheres to the project's coding and style guidelines.
=> Fix TraceRoute notification navigation to correct node (#1115)

Meshtastic/Helpers/LocationsHandler.swift, Meshtastic/Helpers/MeshPackets.swift
Stops making duplicates of waypoints instead of updating a waypoint. Also updates the notification of a new waypoint to show who sent it.
An update/deletion of a waypoint created a duplicate of that same waypoint as the packet.id was used for the waypoint id instead of the actual waypoint id.
Tested on my iPhone, sending, receiving, and modifying waypoints.
Realtime updating and deletion of a waypoint:
https://github.com/user-attachments/assets/6738abee-ef08-426e-816c-726abff55404
=> Fixed waypoint updating logic and waypoint notification

Localizable.xcstrings, Meshtastic/Extensions/String.swift, Meshtastic/Views/Bluetooth/Connect.swift, Meshtastic/Views/Helpers/BLESignalStrengthIndicator.swift, Meshtastic/Views/Helpers/BatteryCompact.swift, Meshtastic/Views/Helpers/BatteryGauge.swift, Meshtastic/Views/Helpers/ConnectedDevice.swift, Meshtastic/Views/Messages/TextMessageField/RequestPositionButton.swift, Meshtastic/Views/Messages/TextMessageField/TextMessageSize.swift, Meshtastic/Views/Nodes/Helpers/Actions/IgnoreNodeButton.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift, Meshtastic/Views/Nodes/Helpers/NodeListItem.swift, Meshtastic/Views/Nodes/NodeList.swift
Redo of previous pull-request that broke the Mac build
Added accessibility tags to a lot of the sections that were hard/impossible to navigate without sight.
After sitting with a Visually impaired user understood the lack of enthusiasm with the Meshtastic radio.
Tested on iphone and this round also on macbook pro.
Ensured there are no visual changes and with VoiceOver my visually impaired tester got it all going now.
Trying to stay out of the hair of the ongoing localization efforts.
=> Additional accessibilityLabels for VoiceOver users (take #2)

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/AppIntents/AddContactIntent.swift, Meshtastic/Extensions/CoreData/NodeInfoEntityToNodeInfo.swift, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Meshtastic.entitlements, Meshtastic/MeshtasticApp.swift, Meshtastic/Views/Nodes/Helpers/ShareContactQRDialog.swift, Meshtastic/Views/Nodes/NodeList.swift, MeshtasticProtobufs/Sources/meshtastic/deviceonly.pb.swift, MeshtasticProtobufs/Sources/meshtastic/mesh.pb.swift, MeshtasticProtobufs/Sources/meshtastic/module_config.pb.swift, MeshtasticProtobufs/Sources/meshtastic/mqtt.pb.swift, MeshtasticProtobufs/Sources/meshtastic/telemetry.pb.swift
Can't actually test the entitlement related url handling changes until it is released to testflight sadly
https://github.com/user-attachments/assets/36912da5-dfcf-4728-8f56-99ed1b7e2132
=> Add share contact via QR (and untested scanning of contact QR codes)

Localizable.xcstrings, Meshtastic/Extensions/String.swift, Meshtastic/Views/Helpers/BLESignalStrengthIndicator.swift, Meshtastic/Views/Helpers/BatteryCompact.swift, Meshtastic/Views/Helpers/BatteryGauge.swift, Meshtastic/Views/Helpers/ConnectedDevice.swift, Meshtastic/Views/Messages/TextMessageField/RequestPositionButton.swift, Meshtastic/Views/Messages/TextMessageField/TextMessageSize.swift, Meshtastic/Views/Nodes/Helpers/Actions/IgnoreNodeButton.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift, Meshtastic/Views/Nodes/Helpers/NodeInfoItem.swift, Meshtastic/Views/Nodes/Helpers/NodeListItem.swift, Meshtastic/Views/Nodes/NodeList.swift
Redo of previous pull-request with fix for infinite recursion that was happening on Mac.
Added accessibility tags to a lot of the sections that were hard/impossible to navigate without sight.
After sitting with a Visually impaired user understood the lack of enthusiasm with the Meshtastic radio.
Tested on both iphone and macbook pro.
Ensured there are no visual changes and with VoiceOver my visually impaired tester got it all going now.
Trying to stay out of the hair of the ongoing localization efforts.
@garthvh believe I finally got to the bottom of it. After some lengthy debugging found the code was crashing with a very deep stack (more 40 thousand deep). i.e. some unwanted recursion going on. 
Culprit is the Divided wrapper extension in BLESignalStrengthIndicator.swift being applied …
=> Additional accessibilityLabels for VoiceOver users (take #3)

Localizable.xcstrings, Meshtastic/Extensions/UserDefaults.swift, Meshtastic/Views/Nodes/Helpers/Map/MapContent/MeshMapContent.swift, Meshtastic/Views/Nodes/Helpers/Map/MapSettingsForm.swift
Added an option to filter by only favorite nodes on the map
In large meshes, when you want to just focus on your important nodes. Also encourages the use of favorite.
Tested by checking and unchecking with large numbers of nodes.
=> Added Favorites Only Map Option

Meshtastic/Extensions/CoreData/ChannelEntityExtension.swift, Meshtastic/Views/Messages/ChannelList.swift
Changed channels to a fetch request, added a visual indicator if a channel is muted. Also, fixed the channel saving logic to save channels even if they are muted.
Before, channel mute settings were remaining unchanged even when in the code the channel was muted, also the mute status of the channel was not actually saving to the device and not persisting.
Sent a message from another n0ode and switched to the node where that channel was muted.
https://github.com/user-attachments/assets/e36ce8e4-75d5-4592-860d-84a4fbd0a692
=> Fixed the persistence of channel mute settings

Meshtastic/Views/Messages/ChannelMessageList.swift, Meshtastic/Views/Messages/UserMessageList.swift
Made it so if unread count is 0 go to bottom.
Issue reported by Jason.
Before:
https://github.com/user-attachments/assets/ff87eb62-9004-4bf7-858a-a6d58d920472
After Fix:
https://github.com/user-attachments/assets/1d1e1f03-b10c-4a4d-bc1f-3cc26bbeacae
https://github.com/user-attachments/assets/7939be4d-e16f-471c-a849-9cdaad49831c
=> If no unread messages go straight to bottom

Meshtastic/Helpers/BLEManager.swift
Small change to reset the wantConfig countdown when the node is disconnected
=> Reset wantConfigRetries on disconnect

Meshtastic/Views/Helpers/SecureInput.swift, Meshtastic/Views/Settings/Config/SecurityConfig.swift
1. Updated `SecureInput` to optionally take a binding for `isSecure` allowing the parent view to see/change the whether the field is masked or viewable free text.
2. Use this new binding to unmask the field when a new key is generated.
3. Added `generatePublicKey` function to take a private Curve25519 key and generate the public key.
4. Use this new function to generate the public key when the private key changes, and highlight the public key in red when the key pair is not valid.
General usability improvements
More testing needed
=> Security settings improvements

Meshtastic/Helpers/BLEManager.swift
First send heartbeat and then wantConfig, also disconnect node after failures to prevent a user being trapped with a forver connecting node.
This prevents the node from ignoring wantConfig as sometimes they come back to back.
Tested by connecting to node
=> Fixed connection issues 

Meshtastic/Helpers/BLEManager.swift, Meshtastic/Views/Bluetooth/Connect.swift
Automatically disconnnect after 6 6 second want config failures so that the insufficient encryption error has a chance to fire if the pin dialog is left open.
=> Additional Connection timing updates

Localizable.xcstrings, Meshtastic/Helpers/BLEManager.swift, Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Persistence/UpdateCoreData.swift, Meshtastic/Views/Settings/AppSettings.swift
Add an option to the App Setting to purge nodes entities after they haven't been heard for a certain
number of days.
This purges entries from the app's node list, but not from the connected node.
This will not clear out nodes that have been favorited or ignored
Create a periodic task to check for stale node entries and delete them.
I'm in an area where there quite a few nodes coming and going. Node lists in the app can get into the 200-300 range pretty quickly. As a result, we end up with quite a few stale node entities in the app DB.
A number of folks in the area regularly clear their node DB to clear out the stale nodes. This would help manage that.
Have been running with various stale times and favorite, ignored settings. Ensured only the expected nodes were deleted.
=> App option for purging nodes not heard in certain amount of time

Localizable.xcstrings, Meshtastic.xcodeproj/project.pbxproj, Meshtastic/AppIntents/FactoryResetNodeIntent.swift, Meshtastic/AppIntents/RestartNodeIntent.swift
Added the option for a hard reset in factory reset intent and an option not to have a confirmation dialogue. Removed confirmation dialogue from restart intent as it is not that destructive.
Added more functionality for people to create "kill switches" for nodes. Also easier to do reboots now.
Factory reset is not tested as I did not find a sacrificial node.
=> Update factory reset and restart intents

Meshtastic/Helpers/MeshPackets.swift, Meshtastic/Views/Settings/Config/Module/CannedMessagesConfig.swift
Fix issues #1279 
Not showing canned messages from the node device.
=> Fix not showing canned messages and message changed detection

.github/workflows/macos-dSYM.yml, Meshtastic/MeshtasticApp.swift, Meshtastic/Views/Nodes/Helpers/NodeDetail.swift
Fetch the security config pub key for connected nodes instead of through the node db
Sometimes, when you change the public key of your node, it only changes in the security config. Therefore, we now always fetch the key from the security config for connected nodes.
=> Fix issue where wrong pub key copied for connected node

Meshtastic/Views/Nodes/NodeList.swift
Tie the sheet showing to shareContactNode instead of a isShowing boolean
On the first attempt, a race condition would happen and the share qr code would not work.
Tested on my iPhone
=> Fix qr code not showing

Meshtastic/Views/Messages/ChannelMessageList.swift, Meshtastic/Views/Messages/UserMessageList.swift
Remove redundant gotFirstUnreadMessage variable, which prevents everything from being set as read until it is true
This could improve performance, as everything will be marked as read on load instead of only when scrolled to the first unread item.
Tested on my iPhone
=> Remove redundant gotFirstUnreadMessage 

Meshtastic/Accessory/Accessory Manager/AccessoryManager+Connect.swift, Meshtastic/Accessory/Accessory Manager/AccessoryManager+ToRadio.swift
sendTime was overlooked during the implementation of transports.
Added it back and added it to the connection process to sync the device time
Bug fix
Heltec Mesh Pocket was reset, had 0:00 time and then time was set after connection
=> Reimplemented sendTime() and sendTime on connect

Meshtastic/Views/Messages/ChannelMessageList.swift
Only run the reading logic if the message is unread. This saves performance as we do not run context refreshes on all messages
=> Only mark messages as read if they are unread

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Inner Circle.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Inner Stroke.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Middle Circle.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Middle Stroke 3.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Outer Circle.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid Outer Stroke 2.svg, Meshtastic/Resources/AppIcon.icon/Assets/Icon Grid.svg, Meshtastic/Resources/AppIcon.icon/Assets/Meshtastic Logo.svg, Meshtastic/Resources/AppIcon.icon/icon.json, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Inner Circle.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Inner Stroke.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Middle Circle.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Middle Stroke 3.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Outer Circle.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid Outer Stroke 2.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Icon Grid.svg, Meshtastic/Resources/AppIconDebug.icon/Assets/Meshtastic Logo.svg, Meshtastic/Resources/AppIconDebug.icon/icon.json
- Added Icon Composer based icons for OS26.
- Updated `Asset Catalog Other` flags to `--enable-icon-stack-fallback-generation=disabled` to prevent Xcode from rendering the Icon Composer icon for previous versions of iOS.   This can be removed if we want to standardize icons across older OS versions.  With this flag, the original PNG asset catalog icons will be used on versions prior to OS26
Gotta change with the times
- iOS simulator on both iOS 18 iOS26
- iPhone 16 Pro running iOS26 Beta 8
- MacOS running iOS26 Beta 8. (note you might need to clean build folders/trash derived data to get the icon to update)
=> Icon Composer Icon

Meshtastic.xcodeproj/project.pbxproj, Meshtastic/Accessory/Accessory Manager/AccessoryManager+Connect.swift, Meshtastic/Accessory/Accessory Manager/AccessoryManager+FromRadio.swift, Meshtastic/Accessory/Protocols/Device.swift, Meshtastic/Extensions/Logger+DataDog.swift, Meshtastic/MeshtasticApp.swift
Added action logging on connect events. This will allow us to collect metrics on node hardware models, transport usage, and initial node DB size.
Also added a "datadog" logger (`Logger.datadog`) , which will emit log messages into both the local OSLogger as well as DataDog's live tail.  Note, however, that this should be only used for public log messages.  Secret or senstive information should not be sent to the DataDog logger.
Better logging
Locally on iOS26
=> DataDog action logging
